### ISSUE TITLE
Does slambench work on cuda8.0?

### ISSUE THREAD

**Issue by HTLife** [pamela-project/slambench1#4]
This is what I got when I tried to build the project.
It seems that the problem is related to cuda.
```
➜  build make
[  1%] Building NVCC (Device) object kfusion/CMakeFiles/kfusion-cuda.dir/src/cuda/kfusion-cuda_generated_kernels.cu.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/local/include/TooN/internal/allocator.hh(185): error: expected a ";"

/usr/local/include/TooN/internal/vector.hh(150): error: expected a ";"

/usr/local/include/TooN/internal/operators.hh(84): error: function template "TooN::Internal::gettype" is not a type name

/usr/local/include/TooN/internal/operators.hh(84): error: expected a ")"

/usr/local/include/TooN/internal/operators.hh(84): error: expected a ";"

/usr/local/include/TooN/internal/operators.hh(85): error: function template "TooN::Internal::gettype" is not a type name

/usr/local/include/TooN/internal/operators.hh(85): error: expected a ")"

/usr/local/include/TooN/internal/operators.hh(85): error: expected a ";"

/usr/local/include/TooN/internal/operators.hh(86): error: function template "TooN::Internal::gettype" is not a type name

/usr/local/include/TooN/internal/operators.hh(86): error: expected a ")"

/usr/local/include/TooN/internal/operators.hh(86): error: expected a ";"

/usr/local/include/TooN/internal/operators.hh(87): error: function template "TooN::Internal::gettype" is not a type name

/usr/local/include/TooN/internal/operators.hh(87): error: expected a ")"

/usr/local/include/TooN/internal/operators.hh(87): error: expected a ";"

/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(459): error: more than one operator "*" matches these operands:
            function template "TooN::Matrix<R, C, TooN::Internal::Multiply::Return<P1, P2>::Type, TooN::RowMajor> TooN::operator*(const TooN::Matrix<R, C, P1, B1> &, const P2 &)"
            function template "TooN::Matrix<R, C, TooN::Internal::Multiply::Return<P2, P1>::Type, TooN::RowMajor> TooN::operator*(const P2 &, const TooN::Matrix<R, C, P1, B1> &)"
            operand types are: const TooN::Matrix<4, 4, const float, TooN::Reference::RowMajor> * const TooN::Matrix<4, 4, const float, TooN::Reference::RowMajor>

/usr/local/include/TooN/internal/operators.hh(106): error: class "TooN::Internal::MultiplyType<float, float, 1>" has no member "type"
          detected during:
            instantiation of class "TooN::Internal::Multiply::Return<P1, P2> [with P1=float, P2=float]" 
/usr/local/include/TooN/gaussian_elimination.h(144): here
            instantiation of "TooN::Matrix<TooN::Internal::Size3<R1, C1, R2>::s, C2, Precision, TooN::RowMajor> TooN::gaussian_elimination(TooN::Matrix<R1, C1, Precision, TooN::RowMajor>, TooN::Matrix<R2, C2, Precision, TooN::RowMajor>) [with R1=4, C1=4, R2=4, C2=4, Precision=float]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(483): here

/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(517): error: no instance of overloaded function "TooN::GR_SVD<M, N, Precision, WANT_U, WANT_V>::backsub [with M=6, N=6, Precision=TooN::DefaultPrecision, WANT_U=true, WANT_V=true]" matches the argument list
            argument types are: (const TooN::Vector<6, TooN::DefaultPrecision, TooN::Internal::VBase>, double)
            object type is: TooN::GR_SVD<6, 6, TooN::DefaultPrecision, true, true>

/usr/local/include/TooN/se3.h(402): error: more than one operator "*" matches these operands:
            function template "TooN::Vector<Size, TooN::Internal::Multiply::Return<P1, P2>::Type, TooN::Internal::VBase> TooN::operator*(const TooN::Vector<Size, P1, B1> &, const P2 &)"
            function template "TooN::Vector<Size, TooN::Internal::Multiply::Return<P2, P1>::Type, TooN::Internal::VBase> TooN::operator*(const P2 &, const TooN::Vector<Size, P1, B1> &)"
            operand types are: const TooN::Vector<3, TooN::DefaultPrecision, TooN::Internal::VBase> * const TooN::Vector<3, TooN::DefaultPrecision, TooN::Internal::VBase>
          detected during:
            instantiation of "TooN::SE3<Precision> TooN::SE3<Precision>::exp(const TooN::Vector<S, P, A> &) [with Precision=TooN::DefaultPrecision, S=6, P=TooN::DefaultPrecision, A=TooN::Internal::VBase]" 
(56): here
            instantiation of "TooN::SE3<Precision>::SE3(const TooN::Vector<S, P, A> &) [with Precision=TooN::DefaultPrecision, S=6, P=TooN::DefaultPrecision, A=TooN::Internal::VBase]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(708): here

/usr/local/include/TooN/se3.h(406): error: no operator "^" matches these operands
            operand types are: const TooN::Vector<3, TooN::DefaultPrecision, TooN::Internal::VBase> ^ const TooN::Vector<3, const TooN::DefaultPrecision, TooN::Internal::SliceVBase<1, const double *, const double *, const double &, const double &>>
          detected during:
            instantiation of "TooN::SE3<Precision> TooN::SE3<Precision>::exp(const TooN::Vector<S, P, A> &) [with Precision=TooN::DefaultPrecision, S=6, P=TooN::DefaultPrecision, A=TooN::Internal::VBase]" 
(56): here
            instantiation of "TooN::SE3<Precision>::SE3(const TooN::Vector<S, P, A> &) [with Precision=TooN::DefaultPrecision, S=6, P=TooN::DefaultPrecision, A=TooN::Internal::VBase]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(708): here

/usr/local/include/TooN/internal/operators.hh(106): error: class "TooN::Internal::MultiplyType<double, TooN::DefaultPrecision, 1>" has no member "type"
          detected during:
            instantiation of class "TooN::Internal::Multiply::Return<P1, P2> [with P1=double, P2=TooN::DefaultPrecision]" 
/usr/local/include/TooN/se3.h(410): here
            instantiation of "TooN::SE3<Precision> TooN::SE3<Precision>::exp(const TooN::Vector<S, P, A> &) [with Precision=TooN::DefaultPrecision, S=6, P=TooN::DefaultPrecision, A=TooN::Internal::VBase]" 
/usr/local/include/TooN/se3.h(56): here
            instantiation of "TooN::SE3<Precision>::SE3(const TooN::Vector<S, P, A> &) [with Precision=TooN::DefaultPrecision, S=6, P=TooN::DefaultPrecision, A=TooN::Internal::VBase]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(708): here

/usr/local/include/TooN/se3.h(423): error: no operator "^" matches these operands
            operand types are: const TooN::Vector<3, TooN::DefaultPrecision, TooN::Internal::VBase> ^ const TooN::Vector<3, TooN::DefaultPrecision, TooN::Internal::VBase>
          detected during:
            instantiation of "TooN::SE3<Precision> TooN::SE3<Precision>::exp(const TooN::Vector<S, P, A> &) [with Precision=TooN::DefaultPrecision, S=6, P=TooN::DefaultPrecision, A=TooN::Internal::VBase]" 
(56): here
            instantiation of "TooN::SE3<Precision>::SE3(const TooN::Vector<S, P, A> &) [with Precision=TooN::DefaultPrecision, S=6, P=TooN::DefaultPrecision, A=TooN::Internal::VBase]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(708): here

/usr/local/include/TooN/se3.h(423): error: no instance of overloaded function "TooN::operator*" matches the argument list
            argument types are: (TooN::DefaultPrecision, <error-type>)
          detected during:
            instantiation of "TooN::SE3<Precision> TooN::SE3<Precision>::exp(const TooN::Vector<S, P, A> &) [with Precision=TooN::DefaultPrecision, S=6, P=TooN::DefaultPrecision, A=TooN::Internal::VBase]" 
(56): here
            instantiation of "TooN::SE3<Precision>::SE3(const TooN::Vector<S, P, A> &) [with Precision=TooN::DefaultPrecision, S=6, P=TooN::DefaultPrecision, A=TooN::Internal::VBase]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(708): here

/usr/local/include/TooN/internal/allocator.hh(112): error: incomplete type is not allowed
          detected during:
            instantiation of class "TooN::Internal::StaticSizedAllocator<Size, Precision> [with Size=16, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>]" 
(533): here
            instantiation of class "TooN::Internal::MatrixAlloc<R, C, Precision, FullyStatic> [with R=4, C=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, FullyStatic=true]" 
/usr/local/include/TooN/internal/mbase.hh(80): here
            instantiation of class "TooN::Internal::GenericMBase<Rows, Cols, Precision, RowStride, ColStride, Mem> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, RowStride=4, ColStride=1, Mem=TooN::Internal::MatrixAlloc<4, 4, TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, true>]" 
/usr/local/include/TooN/internal/mbase.hh(260): here
            instantiation of class "TooN::RowMajor::MLayout<Rows, Cols, Precision> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>]" 
/usr/local/include/TooN/internal/matrix.hh(105): here
            instantiation of class "TooN::Matrix<Rows, Cols, Precision, Layout> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Layout=TooN::RowMajor]" 
/usr/local/include/TooN/internal/operators.hh(613): here
            instantiation of "TooN::Matrix<R, C, TooN::Internal::Multiply::Return<P2, P1>::Type, TooN::RowMajor> TooN::operator*(const P2 &, const TooN::Matrix<R, C, P1, B1> &) [with R=4, C=4, P1=float, B1=TooN::RowMajor, P2=TooN::SE3<TooN::DefaultPrecision>]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(467): here
            instantiation of "Matrix4 toMatrix4(const TooN::SE3<P> &) [with P=TooN::DefaultPrecision]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(709): here

/usr/local/include/TooN/internal/allocator.hh(112): error: incomplete type is not allowed
          detected during:
            instantiation of class "TooN::Internal::StaticSizedAllocator<Size, Precision> [with Size=16, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>]" 
(533): here
            instantiation of class "TooN::Internal::MatrixAlloc<R, C, Precision, FullyStatic> [with R=4, C=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, FullyStatic=true]" 
/usr/local/include/TooN/internal/mbase.hh(80): here
            instantiation of class "TooN::Internal::GenericMBase<Rows, Cols, Precision, RowStride, ColStride, Mem> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, RowStride=4, ColStride=1, Mem=TooN::Internal::MatrixAlloc<4, 4, TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, true>]" 
/usr/local/include/TooN/internal/mbase.hh(260): here
            instantiation of class "TooN::RowMajor::MLayout<Rows, Cols, Precision> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>]" 
/usr/local/include/TooN/internal/matrix.hh(105): here
            instantiation of class "TooN::Matrix<Rows, Cols, Precision, Layout> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Layout=TooN::RowMajor]" 
/usr/local/include/TooN/internal/operators.hh(613): here
            instantiation of "TooN::Matrix<R, C, TooN::Internal::Multiply::Return<P2, P1>::Type, TooN::RowMajor> TooN::operator*(const P2 &, const TooN::Matrix<R, C, P1, B1> &) [with R=4, C=4, P1=float, B1=TooN::RowMajor, P2=TooN::SE3<TooN::DefaultPrecision>]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(467): here
            instantiation of "Matrix4 toMatrix4(const TooN::SE3<P> &) [with P=TooN::DefaultPrecision]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(709): here

/usr/local/include/TooN/internal/allocator.hh(553): error: class "TooN::Internal::StaticSizedAllocator<16, TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>>" has no member "my_data"
          detected during:
            instantiation of class "TooN::Internal::MatrixAlloc<R, C, Precision, FullyStatic> [with R=4, C=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, FullyStatic=true]" 
/usr/local/include/TooN/internal/mbase.hh(80): here
            instantiation of class "TooN::Internal::GenericMBase<Rows, Cols, Precision, RowStride, ColStride, Mem> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, RowStride=4, ColStride=1, Mem=TooN::Internal::MatrixAlloc<4, 4, TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, true>]" 
/usr/local/include/TooN/internal/mbase.hh(260): here
            instantiation of class "TooN::RowMajor::MLayout<Rows, Cols, Precision> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>]" 
/usr/local/include/TooN/internal/matrix.hh(105): here
            instantiation of class "TooN::Matrix<Rows, Cols, Precision, Layout> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Layout=TooN::RowMajor]" 
/usr/local/include/TooN/internal/operators.hh(613): here
            instantiation of "TooN::Matrix<R, C, TooN::Internal::Multiply::Return<P2, P1>::Type, TooN::RowMajor> TooN::operator*(const P2 &, const TooN::Matrix<R, C, P1, B1> &) [with R=4, C=4, P1=float, B1=TooN::RowMajor, P2=TooN::SE3<TooN::DefaultPrecision>]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(467): here
            instantiation of "Matrix4 toMatrix4(const TooN::SE3<P> &) [with P=TooN::DefaultPrecision]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(709): here

/usr/local/include/TooN/internal/mbase.hh(130): error: class "TooN::Internal::MatrixAlloc<4, 4, TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, true>" has no member "my_data"
          detected during:
            instantiation of class "TooN::Internal::GenericMBase<Rows, Cols, Precision, RowStride, ColStride, Mem> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, RowStride=4, ColStride=1, Mem=TooN::Internal::MatrixAlloc<4, 4, TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, true>]" 
(260): here
            instantiation of class "TooN::RowMajor::MLayout<Rows, Cols, Precision> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>]" 
/usr/local/include/TooN/internal/matrix.hh(105): here
            instantiation of class "TooN::Matrix<Rows, Cols, Precision, Layout> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Layout=TooN::RowMajor]" 
/usr/local/include/TooN/internal/operators.hh(613): here
            instantiation of "TooN::Matrix<R, C, TooN::Internal::Multiply::Return<P2, P1>::Type, TooN::RowMajor> TooN::operator*(const P2 &, const TooN::Matrix<R, C, P1, B1> &) [with R=4, C=4, P1=float, B1=TooN::RowMajor, P2=TooN::SE3<TooN::DefaultPrecision>]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(467): here
            instantiation of "Matrix4 toMatrix4(const TooN::SE3<P> &) [with P=TooN::DefaultPrecision]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(709): here

/usr/local/include/TooN/internal/matrix.hh(109): error: class "TooN::RowMajor::MLayout<4, 4, TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>>" has no member "my_data"
          detected during:
            instantiation of class "TooN::Matrix<Rows, Cols, Precision, Layout> [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Layout=TooN::RowMajor]" 
/usr/local/include/TooN/internal/operators.hh(613): here
            instantiation of "TooN::Matrix<R, C, TooN::Internal::Multiply::Return<P2, P1>::Type, TooN::RowMajor> TooN::operator*(const P2 &, const TooN::Matrix<R, C, P1, B1> &) [with R=4, C=4, P1=float, B1=TooN::RowMajor, P2=TooN::SE3<TooN::DefaultPrecision>]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(467): here
            instantiation of "Matrix4 toMatrix4(const TooN::SE3<P> &) [with P=TooN::DefaultPrecision]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(709): here

/usr/local/include/TooN/internal/mbase.hh(137): error: identifier "my_data" is undefined
          detected during:
            instantiation of "Precision &TooN::Internal::GenericMBase<Rows, Cols, Precision, RowStride, ColStride, Mem>::operator()(int, int) [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, RowStride=4, ColStride=1, Mem=TooN::Internal::MatrixAlloc<4, 4, TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, true>]" 
/usr/local/include/TooN/internal/operators.hh(599): here
            instantiation of "void TooN::Operator<TooN::Internal::ApplyScalarML<R, C, P1, B1, P2, Op>>::eval(TooN::Matrix<R0, C0, P0, Ba0> &) const [with R=4, C=4, P1=float, B1=TooN::RowMajor, P2=TooN::SE3<TooN::DefaultPrecision>, Op=TooN::Internal::Multiply, R0=4, C0=4, P0=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Ba0=TooN::RowMajor]" 
/usr/local/include/TooN/internal/matrix.hh(149): here
            instantiation of "TooN::Matrix<Rows, Cols, Precision, Layout>::Matrix(const TooN::Operator<Op> &) [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Layout=TooN::RowMajor, Op=TooN::Internal::ApplyScalarML<4, 4, float, TooN::RowMajor, TooN::SE3<TooN::DefaultPrecision>, TooN::Internal::Multiply>]" 
/usr/local/include/TooN/internal/operators.hh(614): here
            instantiation of "TooN::Matrix<R, C, TooN::Internal::Multiply::Return<P2, P1>::Type, TooN::RowMajor> TooN::operator*(const P2 &, const TooN::Matrix<R, C, P1, B1> &) [with R=4, C=4, P1=float, B1=TooN::RowMajor, P2=TooN::SE3<TooN::DefaultPrecision>]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(467): here
            instantiation of "Matrix4 toMatrix4(const TooN::SE3<P> &) [with P=TooN::DefaultPrecision]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(709): here

/usr/local/include/TooN/internal/operators.hh(599): error: no instance of function template "TooN::Internal::Multiply::op" matches the argument list
            argument types are: (const TooN::SE3<TooN::DefaultPrecision>, const float)
          detected during:
            instantiation of "void TooN::Operator<TooN::Internal::ApplyScalarML<R, C, P1, B1, P2, Op>>::eval(TooN::Matrix<R0, C0, P0, Ba0> &) const [with R=4, C=4, P1=float, B1=TooN::RowMajor, P2=TooN::SE3<TooN::DefaultPrecision>, Op=TooN::Internal::Multiply, R0=4, C0=4, P0=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Ba0=TooN::RowMajor]" 
/usr/local/include/TooN/internal/matrix.hh(149): here
            instantiation of "TooN::Matrix<Rows, Cols, Precision, Layout>::Matrix(const TooN::Operator<Op> &) [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Layout=TooN::RowMajor, Op=TooN::Internal::ApplyScalarML<4, 4, float, TooN::RowMajor, TooN::SE3<TooN::DefaultPrecision>, TooN::Internal::Multiply>]" 
(614): here
            instantiation of "TooN::Matrix<R, C, TooN::Internal::Multiply::Return<P2, P1>::Type, TooN::RowMajor> TooN::operator*(const P2 &, const TooN::Matrix<R, C, P1, B1> &) [with R=4, C=4, P1=float, B1=TooN::RowMajor, P2=TooN::SE3<TooN::DefaultPrecision>]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(467): here
            instantiation of "Matrix4 toMatrix4(const TooN::SE3<P> &) [with P=TooN::DefaultPrecision]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(709): here

/usr/local/include/TooN/internal/mbase.hh(169): error: identifier "my_data" is undefined
          detected during:
            instantiation of "const TooN::Internal::GenericMBase<Rows, Cols, Precision, RowStride, ColStride, Mem>::CVec TooN::Internal::GenericMBase<Rows, Cols, Precision, RowStride, ColStride, Mem>::operator[](int) const [with Rows=4, Cols=4, Precision=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, RowStride=4, ColStride=1, Mem=TooN::Internal::MatrixAlloc<4, 4, TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, true>]" 
/usr/local/include/TooN/internal/matrix.hh(192): here
            instantiation of "TooN::Matrix<Rows, Cols, Precision, Layout> &TooN::Matrix<Rows, Cols, Precision, Layout>::operator=(const TooN::Matrix<Rows2, Cols2, Precision2, Base2> &) [with Rows=4, Cols=4, Precision=float, Layout=TooN::Reference::RowMajor, Rows2=4, Cols2=4, Precision2=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Base2=TooN::RowMajor]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(467): here
            instantiation of "Matrix4 toMatrix4(const TooN::SE3<P> &) [with P=TooN::DefaultPrecision]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(709): here

/usr/local/include/TooN/internal/vbase.hh(151): error: expression must be a pointer to a complete object type
          detected during:
            instantiation of "TooN::Internal::GenericVBase<Size, Precision, Stride, Mem>::ConstReferenceType TooN::Internal::GenericVBase<Size, Precision, Stride, Mem>::operator[](int) const [with Size=4, Precision=const TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Stride=1, Mem=TooN::Internal::VectorSlice<4, const TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, const TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float> *, const TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float> *, const TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float> &, const TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float> &>]" 
/usr/local/include/TooN/internal/matrix.hh(192): here
            instantiation of "TooN::Matrix<Rows, Cols, Precision, Layout> &TooN::Matrix<Rows, Cols, Precision, Layout>::operator=(const TooN::Matrix<Rows2, Cols2, Precision2, Base2> &) [with Rows=4, Cols=4, Precision=float, Layout=TooN::Reference::RowMajor, Rows2=4, Cols2=4, Precision2=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Base2=TooN::RowMajor]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(467): here
            instantiation of "Matrix4 toMatrix4(const TooN::SE3<P> &) [with P=TooN::DefaultPrecision]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(709): here

/usr/local/include/TooN/internal/matrix.hh(192): error: no suitable conversion function from "const TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>" to "float" exists
          detected during:
            instantiation of "TooN::Matrix<Rows, Cols, Precision, Layout> &TooN::Matrix<Rows, Cols, Precision, Layout>::operator=(const TooN::Matrix<Rows2, Cols2, Precision2, Base2> &) [with Rows=4, Cols=4, Precision=float, Layout=TooN::Reference::RowMajor, Rows2=4, Cols2=4, Precision2=TooN::These_Types_Do_Not_Form_A_Field<TooN::SE3<TooN::DefaultPrecision>, float>, Base2=TooN::RowMajor]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(467): here
            instantiation of "Matrix4 toMatrix4(const TooN::SE3<P> &) [with P=TooN::DefaultPrecision]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(709): here

/usr/local/include/TooN/helpers.h(99): error: more than one operator "*" matches these operands:
            function template "TooN::Vector<Size, TooN::Internal::Multiply::Return<P1, P2>::Type, TooN::Internal::VBase> TooN::operator*(const TooN::Vector<Size, P1, B1> &, const P2 &)"
            function template "TooN::Vector<Size, TooN::Internal::Multiply::Return<P2, P1>::Type, TooN::Internal::VBase> TooN::operator*(const P2 &, const TooN::Vector<Size, P1, B1> &)"
            operand types are: const TooN::Vector<6, TooN::DefaultPrecision, TooN::Internal::VBase> * const TooN::Vector<6, TooN::DefaultPrecision, TooN::Internal::VBase>
          detected during instantiation of "Precision TooN::norm(const TooN::Vector<Size, Precision, Base> &) [with Size=6, Precision=TooN::DefaultPrecision, Base=TooN::Internal::VBase]" 
/home/jacky/code/SLAMBench_1_1/kfusion/src/cuda/kernels.cu(729): here

33 errors detected in the compilation of "/tmp/tmpxft_00001b32_00000000-7_kernels.cpp1.ii".
CMake Error at kfusion-cuda_generated_kernels.cu.o.cmake:266 (message):
  Error generating file
  /home/jacky/code/SLAMBench_1_1/build/kfusion/CMakeFiles/kfusion-cuda.dir/src/cuda/./kfusion-cuda_generated_kernels.cu.o


kfusion/CMakeFiles/kfusion-cuda.dir/build.make:63: recipe for target 'kfusion/CMakeFiles/kfusion-cuda.dir/src/cuda/kfusion-cuda_generated_kernels.cu.o' failed
make[2]: *** [kfusion/CMakeFiles/kfusion-cuda.dir/src/cuda/kfusion-cuda_generated_kernels.cu.o] Error 1
CMakeFiles/Makefile2:158: recipe for target 'kfusion/CMakeFiles/kfusion-cuda.dir/all' failed
make[1]: *** [kfusion/CMakeFiles/kfusion-cuda.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by bbodin** [comment]
Hi,

I reproduced the bug, this is related to TooN and the way we "compiled" it. 
To fix the bug I had to configure the TooN headers using the following arguments:
` ./configure  --disable-lapack --enable-typeof=decltype`

Now another error can occur (it did for me) with the std::string signature of the dumpVolume function. 
The workaround is to change the string type to const char*.

Both fixes are now pushed on master d1fb35bfc90f4eb52e29c2b6494a83fb2b70ce59.

Cheers,
Bruno

**Comment by HTLife** [comment]
I'd follow the general way to compile the code, which is create a folder for cmake and do cmake for it.
mkdir build
cd build
cmake ..
make

And I found that if I "make" the project under root folder of the project without cmake, I could successfully get the built binaries.

**Comment by yangautumn43** [comment]
Hi Bruno @bbodin ,
I did run `make deps`; then one issue came after it: Failed to install Pangolin. I fixed it according to [issue](https://github.com/stevenlovegrove/Pangolin/commit/ce7ded2a0701609401b9f9df308d12540e6891a7).
Then, I run `make slambench`, after which I got the error `/usr/local/include/pcl-1.8/pcl/pcl_config.h:19:0: error: "HAVE_OPENNI2" redefined [-Werror]
 #define HAVE_OPENNI2 1`. I fixed it by manually adding `#ifndef HAVE_OPENNI2` to the head of `pcl_config.h` in the original system. After that, I can successfully build and use the software.

I recorded everything happened and I did during the installation in the readme file of the forked [repo](https://github.com/yangautumn/slambench2)
